tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/python'
tap 'homebrew/science'
brew 'autoconf'
brew 'autoenv'
brew 'libpng'
brew 'freetype'
brew 'pkg-config'
brew 'fontconfig'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'pixman'
brew 'cairo'
brew 'git'
brew 'gobject-introspection'
brew 'jpeg'
brew 'xz'
brew 'libtiff'
brew 'shared-mime-info'
brew 'gdk-pixbuf'
brew 'libcroco'
brew 'icu4c'
brew 'harfbuzz'
brew 'pango'
brew 'librsvg'
brew 'emacs'
brew 'cask'
brew 'cctools'
brew 'cmake'
brew 'coreutils'
brew 'doxygen'
brew 'pcre2'
brew 'fish'
brew 'gdbm'
brew 'little-cms2'
brew 'ghostscript'
brew 'go'
brew 'hub'
brew 'hugo'
brew 'openssl'
brew 'libevent'
brew 'libquicktime'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'libxml2'
brew 'libyaml'
brew 'mas'
brew 'moreutils'
brew 'node'
brew 'pandoc'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'pyenv-virtualenvwrapper'
brew 'python3'
brew 'ruby'
brew 'speedtest_cli'
brew 'texi2html'
brew 'utf8proc'
brew 'tmux'
brew 'tree'
brew 'zsh', args: ['without-etcdir']
brew 'zplug'
brew 'homebrew/python/numpy'
cask '1password'
cask 'adobe-illustrator-cc'
cask 'adobe-indesign-cc'
cask 'adobe-photoshop-cc'
cask 'adobe-photoshop-lightroom'
cask 'adobe-photoshop-lightroom600'
cask 'adobe-reader'
cask 'arduino'
cask 'atom'
cask 'dropbox'
cask 'flux'
cask 'gimp'
cask 'google-chrome'
cask 'google-drive'
cask 'iterm2'
cask 'jupyter-notebook-ql'
cask 'makerbot-desktop'
cask 'openframeworks'
cask 'processing'
cask 'processing2'
cask 'qlmarkdown'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'spotify'
cask 'sublime-text'
cask 'thunderbird'
cask 'unity'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'webstorm'
mas 'Numbers', id: 409203825
mas 'Numbers', id: 409203825
mas 'Xcode', id: 497799835
mas 'Keynote', id: 409183694
mas 'Pages', id: 409201541
mas 'Xcode', id: 497799835
mas 'LINE', id: 539883307
mas 'Keynote', id: 409183694
mas 'Pages', id: 409201541
mas 'LINE', id: 539883307
